services:
  web:
    build: .
    restart: always
    environment:
      - NODE_ENV=production
      - DISCORD_WEBHOOK_URL=${DISCORD_WEBHOOK_URL}
      - DISCORD_USER_ID=${DISCORD_USER_ID}
    networks:
      - dokploy-network  # <-- Connects service to Traefik's network
    command: >
      sh -c "node server.js"

# Tells compose this network already exists on the host
networks:
  dokploy-network:
    external: true