services:
  web:
    build: .
    ports:
      - "3000:3000"
    restart: always
    environment:
      - NODE_ENV=production
      - ADMIN_PASSWORD=Kebab@Husova1320
      - DATABASE_URL=file:/app/prisma/db/prod.db
    volumes:
      - portfolio_db:/app/prisma/db
    command: >
      sh -c "npx prisma db push && node server.js"

volumes:
  portfolio_db:
